./simpsh \
    --verbose \
    --rdonly ay \
    --rdonly by \
    --rdonly cy \
    --wronly dy \
    --wronly ey \
    --wronly fy \
    --command 0 3 3 cat \
    --command 2 5 5 tr A-Z a-z \
    --command 1 4 4 sort 
